### PR TITLE
[ADD] Select warehouse for sale order

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Comment by sbidoul** [comment]
@lmignon @Cedric-Pigeon

**Review by lmignon — APPROVED** [review]
:+1:  Make sense

**Comment by Cedric-Pigeon** [comment]
:+1:

**Review by Cedric-Pigeon — APPROVED** [review]
:+1:

**Comment by StefanRijnhart** [comment]
Thanks!

**Pull request merged**
